export const COLUMN_CHART = 'column-chart'
export const ROW_CHART = 'row-chart'
export const RANGE_CHART = 'range-chart'
export const ROUND_CHART = 'round-chart'
export const SAME_DIRECTION_ROUND_CHART = 'same-direction-round-chart'
export const POLYGON_CHART = 'polygon-chart'
export const LINE_CHART = 'line-chart'
export const BUBBLE_CHART = 'bubble-chart'
